{% set name = "expertai-nlapi" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/expertai-nlapi-{{ version }}.tar.gz
  sha256: 3714a55cf86b9afe5e611d9972528568b05b32df47c331d3d8b675795edf9d9b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - requests

test:
  imports:
    - expertai.nlapi.cloud
    - expertai.nlapi.common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/therealexpertai/nlapi-python
  summary: Python client for expert.ai Natural Language API
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Python client for the expert.ai Natural Language APIs adds Natural Language understanding capabilities to your Python apps. 
    The client can use either the Cloud based Natural Language API or a local instance of Edge NL API. 
    For more information on these products, visit our developer portal <https://developer.expert.ai/ui>.
  doc_url: https://docs.expert.ai/

extra:
  recipe-maintainers:
    - zlatev
    - avarone-github
    - marcobellei-eai
    - acapitani
